config/routes.rb
Rails.application.routes.draw do
  devise_for :users 

  resources :wikis

  get 'users/show'

  resources :users, only: [:show, :index] do
    post 'publicize_wiki' => 'users#publicize_wiki', as: :publicize_wiki
    end

  resources :charges, only: [:new, :create]

  get 'welcome/index'
	root to: "welcome#index"
end

app/models/wiki.rb
class Wiki < ApplicationRecord
	belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators
  
  #default_scope { order('created_at DESC') }
  scope :visible_to, -> (user) {user && ((user.role == 'admin') || (user.role == 'premium')) ? all : where(private: false) }
  scope :private_wikis, -> (user) { where(private: true) }

  def public?
  #	!private?
    self.private == false
  end

  def private? 
    self.private == true
  end
end

app/controllers/wikis/confirmations_controller.rb
class Wikis::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/wikis/omniauth_callbacks_controller.rb
class Wikis::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/wikis/passwords_controller.rb
class Wikis::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/wikis/registrations_controller.rb
class Wikis::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/wikis/sessions_controller.rb
class Wikis::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/wikis/unlocks_controller.rb
class Wikis::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    @collaborators = @wiki.users
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki_user = current_user

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to wiki_path(@wiki)
    else
      flash[:error] = "There was a error saving your wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.update_attributes(wiki_params)
      flash[:notice] = "Wiki was updated."
      redirect_to wiki_path(@wiki) 
    else
      flash.now[:alert] = "There was an error saving your wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])  
    authorize @wiki 

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash[:error] = "There was an error deleting your wiki."
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private, user_ids:[])
  end
end

app/helpers/wikis_helper.rb
module WikisHelper
	def user_is_authorized_to_create_and_update_wiki?(wiki)
		current_user && (current_user==wiki.user || current_user.admin? || current_user.premium?)
	end
	
	def user_is_authorized_to_delete?
		current_user && (current_user == wiki.user || current_user.admin?)
	end
	
end

app/views/wikis/_collaborators.html.erb
<h4>Collaborators</h4>
  <table class="table">
    <% @wiki.collaborators.each do |collaborator| %>
      <tr>
        <td><%= collaborator.user.email %></td>
        <td><%= link_to 'Remove Collaborator', wiki_collaborators_path(collaborator.id), method: :delete, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </table>
  <%= link_to "Add Collaborator", wiki_collaborators_path(wiki_id: wiki), class: 'btn btn-success' %> 

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: 'Enter wiki body' %>
  </div>
  <div class="form-group">
    <% if current_user.admin? || current_user.premium? %>
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.label :collaborators %> <br>
    <%= hidden_field_tag "wiki[user_ids][]", nil %>
    <% User.all.each do |user| %>
      <%= check_box_tag "wiki[user_ids][]", user.id, @wiki.users.include?(user), id: dom_id(user) %>
      <%= label_tag dom_id(user), user.email %><br>
    <% end %>
  </div>
    <%= f.submit "Save", class: 'btn btn-success' %> 
  </div>
<% end %>

app/views/wikis/edit.html.erb
<%= link_to "Back to Wikis", @wikis %>
<div class="container">
  <h1>Edit</h1>
    <div class="col-md-8">
      <%= render partial: 'form', locals: { wiki: @wiki, user: @user, collaborators: @collaborators } %>
    </div>
</div>

app/views/wikis/index.html.erb
<h1>Wikis</h1>
  <div class="row">
    <div class="col-md-5">
      <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
    </div>
    <br>
    <div class="col-md-5">
      <% @wikis.each do |wiki| %>
        <div class="media">
          <div class="media-body">
            <div class="media-heading">
              <%= link_to (wiki.title), wiki %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/wikis/new.html.erb
<%= link_to 'Back to Wikis', @wiki %>
<h1>New Wiki</h1>
  <div class="col-md-8">
   <%= render partial: 'form', locals: { wiki: @wiki } %>
  </div>

app/views/wikis/show.html.erb
<div class="container">
  <%= link_to "Back to Wikis", wikis_path %>
  <div class="col-md-4">
    <% if policy(@wiki).update? %>
      <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <% end %>
      <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
  </div>
  <h1>
    <%= markdown_to_html @wiki.title %>
  </h1>
    <small>
      <i> Written by: <%= @wiki.user.email %></i>
    </small>
  <div class="row">
    <div class="col-md-8">
      <p><%= markdown_to_html @wiki.body %></p>
    </div>
  </div>

  <div class="col-md-3">
      <h4>Collaborators:</h4>
    <% if current_user.admin? || current_user.premium? %>
      <% @collaborators.each do |collaborator| %>
        <p><%= collaborator.email %></p>
    <% end %>
  <% end %>

</div>