config/routes.rb
Rails.application.routes.draw do
  devise_for :users 

  resources :wikis

  get 'users/show'

  resources :users, only: [:show, :index] do
    post 'publicize_wiki' => 'users#publicize_wiki', as: :publicize_wiki
    end

  resources :charges, only: [:new, :create]

  get 'welcome/index'
	root to: "welcome#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  	<div class="container">
	    <ul class="nav nav-tabs">
		    <li><%= link_to "Blocipedia", root_path %></li>
		    <li><%= link_to "Wikis", wikis_path %></li>
  	    <div class="pull-right user-info">
          <div class="col-md-8">
  		    <% if user_signed_in? %>
  		      Signed in as: <strong><%= link_to current_user.email, user_path(current_user) %></strong> | <%= link_to "Edit Profile", edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
  		    <% else %>
  	  	    <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'%> or
  	  	    <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'%>
  		    <% end %>
  	    </div>
	    </ul>
  	  <% if flash[:notice] %>
    		<div class="alert alert-success">
    			<button type="button" class="close" data-dismiss="alert">&times;</button>
    			<%=flash[:notice] %>
    		</div>
  	  <% elsif flash[:error] %>
    		<div class="alert alert-danger">
    			<button type="button" class="close" data-dismiss="alert">&times;</button>
    			<%= flash[:error] %>
    		</div>
  	  <% elsif flash[:alert] %>
    		<div class="alert alert-warning">
    			<button type="button" class="close" data-dismiss="alert">&times;</button>
    			<%= flash[:alert] %>
  		  </div>
	    <% end %>
	  <%= yield %>
	  </div>
  </body>
</html>